buscoayuda/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Examples:
    # url(r'^$', 'buscoayuda.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('componentes.urls',namespace='independiente')),
    url(r'^admin/', include(admin.site.urls)),
]

componentes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^(?P<value>\d+)/$', views.index_por_servicio, name='index_por_servicio'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^perfil/(?P<value>\d+)/$', views.actualizar_independiente, name='actualizar_independiente'),
    url(r'^get_service/', views.get_service, name='get_service'),
    url(r'^post_register/', views.post_register, name='post_register'),
    url(r'^post_login/', views.post_login, name='post_register'),
    url(r'^servicio/', views.ver_servicios, name='ver_servicios'),
    url(r'^comentario/', views.crear_comentario, name='crear_comentario'),
    url(r'^detalle/(?P<value>\d+)/$', views.detalle_independiente, name='detalleIndependiente'),
    url(r'^independiente/(?P<value>\d+)/comentario/', views.ver_comentarios, name='verComentarios'),

    url(r'^api/login/', views.api_login, name='api_login'),
    url(r'^api/independientes/servicios/(?P<value>\d+)/$', views.api_independientes_por_servicio, name='api_independientes_por_servicio'),
    url(r'^api/independientes/(?P<value>\d+)/comentarios/', views.api_comentarios_por_independiente, name='api_comentarios_por_independiente'),
    url(r'^api/independientes/(?P<value>\d+)/', views.api_independientes_por_id, name='api_independientes_por_id'),
    url(r'^api/independientes/', views.api_independientes, name='api_independientes'),
    url(r'^api/servicios/', views.api_servicios, name='api_servicios'),
    url(r'^api/comentarios/', views.api_comentarios, name='api_comentarios'),
]

componentes/models.py
from __future__ import unicode_literals

from django.db import models


# JD.RUNZA -060216:/Modelo Taller 1 Detalle en Drive


class Servicio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)


class Independiente(models.Model):
    id = models.AutoField(primary_key=True)
    idServicio = models.ForeignKey(Servicio)
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    aniosExperiencia = models.IntegerField()
    foto = models.TextField()
    telefono = models.IntegerField()
    correoElectronico = models.EmailField(max_length=50, unique=True)
    contrasenia = models.CharField(max_length=15)
    fechaRegistro = models.DateTimeField(auto_now_add=True, blank=True)


class Comentario(models.Model):
    id = models.AutoField(primary_key=True)
    idIdependiente = models.ForeignKey(Independiente)
    correoElectronico = models.CharField(max_length=50)
    texto = models.CharField(max_length=1000)

componentes/forms.py
# -*- encoding: utf-8 -*-
from django.forms import ModelForm, TextInput
from django import forms
from .models import Independiente,Servicio


class DetalleIndependienteForm(forms.ModelForm):
    class Meta:
        model = Independiente
        fields = '__all__'
        labels = {
            'idServicio':'Servicio',
            'nombre':'Nombre',
            'apellidos':'Apellidos',
            'aniosExperiencia':'Años de experiencia',
            'telefono':'Teléfono',
            'correoElectronico':'Correo Electronico',
            'fechaRegistro':'Fecha Registro',
        }
        exclude = ['contrasenia']
        widgets = {
            'nombre': TextInput(attrs={'readonly':'readonly'}),
            'apellidos': TextInput(attrs={'readonly':'readonly'}),
            'idServicio': TextInput(attrs={'readonly':'readonly'}),
            'aniosExperiencia': TextInput(attrs={'readonly':'readonly'}),
            'telefono': TextInput(attrs={'readonly':'readonly'}),
            'correoElectronico': TextInput(attrs={'readonly':'readonly'}),
            'foto': TextInput(attrs={'readonly':'readonly'}),
            'foto': forms.HiddenInput()
        }


class IndependienteForm(forms.ModelForm):
   class Meta:
        model = Independiente
        fields = '__all__'
        labels = {
            'idServicio':'Servicio',
            'nombre':'Nombre',
            'apellidos':'Apellidos',
            'aniosExperiencia':'Años de experiencia',
            'telefono':'Teléfono',
            'correoElectronico':'Correo Electronico',
            'fechaRegistro':'Fecha Registro',
        }
        exclude = ['contrasenia', 'idServicio']
        widgets = {
            'correoElectronico': TextInput(attrs={'readonly':'readonly'}),
            'foto': forms.HiddenInput()
        }

        owner = forms.ModelChoiceField(label="Servicio2",
                                  queryset=Servicio.objects.all())

componentes/views.py
import sendgrid
import os
import json
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .forms import DetalleIndependienteForm, IndependienteForm
from .models import Independiente, Comentario, Servicio
from .mail import Mail


def index(request):
    listaidependientes = Independiente.objects.all().order_by('fechaRegistro')
    context = {'listaidependientes': listaidependientes}
    return render(request, 'componentes/index.html', context)


def index_por_servicio(request, value):
    if request.method == 'GET':
        try:
            if value == -1:
                listaidependientes = Independiente.objects.all().order_by('fechaRegistro')
            else:
                id_servicio = value
                listaidependientes = Independiente.objects.filter(idServicio=id_servicio).order_by('fechaRegistro')
                context = {'listaidependientes': listaidependientes}
                return render(request, 'componentes/index.html', context)
        except Exception as e:
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


def register(request):
    return render(request, 'componentes/register.html')


def login(request):
    return render(request, 'componentes/login.html')


def perfil(request):
    return render(request, 'componentes/perfil.html')


@csrf_exempt
def post_register(request):
    try:
        freelance = Independiente(
            nombre=request.POST['nombre'],
            apellidos=request.POST['apellidos'],
            aniosExperiencia=request.POST['aniosExperiencia'],
            idServicio=Servicio.objects.get(id=request.POST['idServicio']),
            telefono=request.POST['telefono'],
            correoElectronico=request.POST['correoElectronico'],
            contrasenia=request.POST['contrasenia'],
            foto=request.POST['foto'])
        freelance.save()
        mail = Mail(freelance.correoElectronico, 'Bienvenido a la comunidad Busco Ayuda!',
                    'Hola ' + freelance.nombre + ', <br><br>En Busco Ayuda puedes inscribir y buscar servicios prestados por independientes en oficios varios! <br><br>Gracias por hacer parte de nuestra comunidad.')
        mail.send()
        return HttpResponse(json.dumps(freelance.id), content_type="application/json", status=200)
    except Exception as e:
        print (e.args)
        return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


@csrf_exempt
def get_service(request):
    try:
        result = serializers.serialize('json', Servicio.objects.all())
        return HttpResponse(result, content_type="application/json", status=200)
    except Exception as e:
        return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


@csrf_exempt
def post_login(request):
    try:
        freelance = Independiente.objects.get(correoElectronico=request.POST['correoElectronico'])
        if (freelance.contrasenia == request.POST['contrasenia']):
            return HttpResponse(json.dumps(freelance.id), content_type="application/json", status=200)
        else:
            return HttpResponse(json.dumps(freelance.correoElectronico + " " + freelance.contrasenia),
                                content_type="application/json", status=401)
    except Exception as e:
        return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


def detalle_independiente(request, value):
    queryset = Independiente.objects.filter(id=value)
    if request.POST:
        form = DetalleIndependienteForm(request.POST, instance=queryset)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        independiente = Independiente.objects.get(id=value)
        form = DetalleIndependienteForm(instance=independiente)
    return render(request, 'componentes/independiente_form.html', {'form': form})


@csrf_exempt
def actualizar_independiente(request, value):
    queryset = Independiente.objects.filter(id=value)
    if request.POST:
        instance = Independiente.objects.get(id=value)
        form = IndependienteForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        independiente = Independiente.objects.get(id=value)
        form = IndependienteForm(instance=independiente)
    return render(request, 'componentes/perfil.html', {'form': form})


@csrf_exempt
def crear_comentario(request):
    if request.method == 'POST':
        try:
            json_comentario = json.loads(request.body)
            id_independiente = json_comentario['idIndependiente']
            correo_electronico = json_comentario['correoElectronico']
            texto = json_comentario['texto']
            freelance = Independiente.objects.get(id=id_independiente)
            nuevo_comentario = Comentario(idIdependiente=freelance, correoElectronico=correo_electronico, texto=texto)
            nuevo_comentario.save()
            mail = Mail(freelance.correoElectronico, 'Nuevo comentario en la comunidad Busco Ayuda!',
                        'Hola ' + freelance.nombre + ', <br><br>Realizaron un nuevo comentario sobre tus servicios: <i>' + texto + ' </i><br><br>Gracias por hacer parte de nuestra comunidad.')
            mail.send()
            return HttpResponse(serializers.serialize('json', [nuevo_comentario]))
        except Exception as e:
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


@csrf_exempt
def ver_comentarios(request, value):
    if request.method == 'GET':
        try:
            comentarios = Comentario.objects.filter(idIdependiente=value)
            return HttpResponse(serializers.serialize('json', comentarios))
        except Exception as e:
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


@csrf_exempt
def ver_independientes_por_filtro(request, value):
    if request.method == 'GET':
        try:
            if value == -1:
                independientes = Independiente.objects.all().order_by('fechaRegistro')
            else:
                id_servicio = value
                independientes = Independiente.objects.filter(idServicio=id_servicio).order_by('fechaRegistro')
            return HttpResponse(serializers.serialize('json', independientes))
        except Exception as e:
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


@csrf_exempt
def ver_servicios(request):
    if request.method == 'GET':
        try:
            servicios = Servicio.objects.all()
            return HttpResponse(serializers.serialize('json', servicios))
        except Exception as e:
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


def api_independientes(request):
    if request.method == 'GET':
        try:
            independientes = Independiente.objects.all().order_by('fechaRegistro')
            return HttpResponse(serializers.serialize('json', independientes))

        except Exception as e:
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)

    elif request.method == 'POST':
        try:
            independiente = Independiente(
                nombre=request.POST['nombre'],
                apellidos=request.POST['apellidos'],
                aniosExperiencia=request.POST['aniosExperiencia'],
                idServicio=Servicio.objects.get(id=request.POST['idServicio']),
                telefono=request.POST['telefono'],
                correoElectronico=request.POST['correoElectronico'],
                contrasenia=request.POST['contrasenia'],
                foto=request.POST['foto'])
            independiente.save()
            mail = Mail(independiente.correoElectronico, 'Bienvenido a la comunidad Busco Ayuda!',
                        'Hola ' + independiente.nombre + ', <br><br>En Busco Ayuda puedes inscribir y buscar servicios prestados por independientes en oficios varios! <br><br>Gracias por hacer parte de nuestra comunidad.')
            mail.send()
            return HttpResponse(json.dumps(independiente.id), content_type="application/json", status=200)
        except Exception as e:
            print (e.args)
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)

def api_independientes_por_id(request, value):
    if request.method == 'GET':
        print value
        independiente = Independiente.objects.get(id=value)
        return HttpResponse(serializers.serialize('json', [independiente]))

    elif request.method == 'PUT':
        try:
            json_independiente = json.loads(request.body)
            independiente = Independiente(
                nombre=json_independiente['nombre'],
                apellidos=json_independiente['apellidos'],
                aniosExperiencia=json_independiente['aniosExperiencia'],
                idServicio=Servicio.objects.get(json_independiente['idServicio']),
                telefono=json_independiente['telefono'],
                correoElectronico=json_independiente['correoElectronico'],
                contrasenia=json_independiente['contrasenia'],
                foto=json_independiente['foto'])
            independiente.save()
            return HttpResponse(json.dumps(independiente.id), content_type="application/json", status=200)
        except Exception as e:
            print (e.args)
            return HttpResponse(json.dumps(e.args), content_type="application/json", status=400)


def api_independientes_por_servicio(request, value):
    if request.method == 'GET':
        try:
            if value == -1:
                independientes = Independiente.objects.all().order_by('fechaRegistro')
            else:

componentes/templates/componentes/base.html
<!DOCTYPE html>
<html lang="en" ng-app="app_buscoayuda">
<head>
    <meta charset="UTF-8">
    {# Cargar tag de librería #}
    {% load bootstrap3 %}
    {# Cargar CSS y JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {# Cargar archivos estáticos#}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <title>Busco Ayuda</title>
    <script type="text/javascript" language="javascript" src="{% static 'js/jquery-1.12.0.min.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/jquery.dataTables.min.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/dataTables.bootstrap.min.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/angular.min.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/modules_angular.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/ng-image-compress.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/ctrl_base.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/ctrl_index.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/ctrl_register.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/ctrl_login.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/ctrl_comentario.js'%}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/ctrl_independiente.js'%}"></script>
</head>
<body>
<header ng-controller="ctrl_base" id="buscoayuda-header" class="container">
    <a href="/"><h1 class="buscoayuda-inline-block">BuscoAyuda <i class="fa fa-bullhorn"></i></h1></a>
    <nav class="right buscoayuda-inline-block">
        <span ng-hide="logged">
            <a href="/">Inicio</a> |
            <a href="/register/">Registrarse</a> |
            <a href="/login/"><i class="fa fa-sign-in"></i> Iniciar sesión</a>
        </span>
        <span ng-show="logged">
            <a href="/">Inicio</a> |
            <a ng-click="makeURL()" >Perfil</a> |
            <a href ng-click="log_out()"><i class="fa fa-sign-out"></i> Cerrar sesión</a>
        </span>
    </nav>
</header>

{% block content %}
{% endblock %}

<footer id="buscoayuda-footer">
    <p>Desarrollado por Grupo 1 Procesos Ágiles Uniandes 2016-10</p>
</footer>
</body>
</html>

componentes/templates/componentes/independiente_form.html
{% extends 'componentes/base.html' %}
{% load mathfilters %}
{# Cargar tag de librería #}
{% load bootstrap3 %}
{# Cargar archivos estáticos#}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="col-md-5 buscoayuda-index-independiente-cont">
            <h1>{{form.idServicio.nombre}}</h1>
            <a> <img src="{{ form.foto.value }}" width="100%"></a>
    </div>
    <div class="col-md-5">

    <table class="buscoayuda-bottom-hr" id="example" cellspacing="0" width="100%">
        <form action="{% url 'independiente:detalleIndependiente' value=0 %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <!--<{% buttons %}
            input type="submit" value="Añadir" class="btn btn-primary btn-block"/>
            {% endbuttons %} -->
        </form>
        </tbody>
    </table>
    <div id="buscoayuda-independiente-comentario-container" ng-controller="ctrl_independiente">
        <label>Comentarios:</label>
        <div class="buscoayuda-independiente-comentario" ng-repeat="c in comentarios">
            <p><b>[[c.fields.correoElectronico]]:</b> [[c.fields.texto]]</p>
        </div>
    </div>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal-comentario">
      Agregar comentario
    </button>

    <!-- Modal -->
    <div class="modal fade" ng-controller="ctrl_comentario" id="modal-comentario" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Agregar comentario</h4>
          </div>
          <form ng-submit="crear_comentario()">
              <div class="modal-body">

                    <div class="form-group">
                        <label for="correoElectronico">Correo electrónico:</label>
                        <input type="email" class="form-control" id="correoElectronico"
                               placeholder="Correo Electrónico" ng-model="comentario.correoElectronico" required maxlength="50">
                    </div>

                    <div class="form-group">
                        <label>Comentario:</label>
                        <textarea class="form-control" rows="4" cols="50" name="texto" ng-model="comentario.texto">
                            Comentario...</textarea>
                    </div>

              </div>
              <div class="modal-footer">
                <input type="submit" class="btn btn-default" value="Agregar">
              </div>
          </form>
        </div>
      </div>
    </div>
    </div>
<script type="text/javascript" language="javascript" src="{% static 'js/index.js'%}"></script>

</div>

{% endblock %}

componentes/templates/componentes/index.html
{% extends 'componentes/base.html' %}
{% load mathfilters %}
{# Cargar archivos estáticos#}
{% load staticfiles %}
{% block content %}

<div class="container" ng-controller="ctrl_index">
    <div id="buscoayuda-index-filter">
        <h2 class="buscoayuda-inline-block">Filtro:</h2>
        <select ng-change="ver_independientes_por_filtro()" ng-model="servicio_seleccionado" class="buscoayuda-inline-block">
            <option value="-1" selected="selected">Todos</option>
            <option ng-repeat="s in servicios" value="[[s.pk]]">[[s.fields.nombre]]</option>
        </select>
    </div>

    <table id="example" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for independiente in listaidependientes %}
            <td width="30%">
                <div class="buscoayuda-index-independiente-cont">
                    <h1>{{independiente.idServicio.nombre}}</h1>
                    <a href="{% url 'independiente:detalleIndependiente' value=independiente.id %}">
                        <img src="{{independiente.foto}}">
                        <p>{{independiente.nombre}} {{independiente.apellidos}}</p>
                    </a>
                </div>
            </td>
            {% if forloop.counter|divisibleby:"3" %}
        </tr>
        <tr>
            {% endif %}
            {% endfor %}

            {% with total=listaidependientes|length %}
            {% with totalcols=total|div:3 %}
            {% with floortotalcols=totalcols|intdiv:1 %}
            {% with resulttotal=totalcols|sub:floortotalcols %}

            {% if resulttotal > 0.5 %}
            <td></td>
            {% endif %}
            {% if resulttotal < 0.5 %}
            <td></td>
            <td></td>
            {% endif %}
            {% if resulttotal == 0 %}
            <td>...</td>
            <td>...</td>
            <td>...</td>
            {% endif %}
            {% endwith %}
            {% endwith %}
            {% endwith %}
            {% endwith %}
        </tr>
        </tbody>
    </table>
</div>

<script type="text/javascript" language="javascript" src="{% static 'js/index.js'%}"></script>

{% endblock %}

componentes/templates/componentes/login.html
{% extends 'componentes/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="container" ng-controller="ctrl_login">

    <form ng-submit="login()">
        <div class="form-group">
            <label for="correoElectronico">Usuario</label>
            <input type="email" class="form-control" id="correoElectronico"
                   placeholder="Correo Electrónico" ng-model="login.correoElectronico" required maxlength="50">
        </div>

        <div class="form-group">
            <label for="contrasenia">Contraseña</label>
            <input type="password" class="form-control" id="contrasenia" placeholder="Contraseña"
                   ng-model="login.contrasenia" required maxlength="15">
        </div>

        <input type="submit" class="btn btn-default" value="Login">
    </form>
</div>

{% endblock %}

componentes/templates/componentes/perfil.html
{% extends 'componentes/base.html' %}
{% load mathfilters %}
{# Cargar tag de librería #}
{% load bootstrap3 %}
{# Cargar archivos estáticos#}
{% load staticfiles %}


{% block content %}
<div class="container">
    <div class="col-md-5 buscoayuda-index-independiente-cont">
            <h1>{{form.idServicio.nombre}}</h1>
            <a> <img src="{{ form.foto.value }}" width="100%"></a>
    </div>

    <div class="col-md-5">
        <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <input type="submit" value="Actualizar" class="btn btn-primary btn-block"/>
            {% endbuttons %}
        </form>

    </div>
<script type="text/javascript" language="javascript" src="{% static 'js/index.js'%}"></script>

</div>

{% endblock %}

componentes/templates/componentes/register.html
{% extends 'componentes/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="container" ng-controller="ctrl_register">
    [[rregister]]
    <form ng-submit="save_register()">

        <div class="col-md-6">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" id="nombre" placeholder="Nombre" ng-model="register.nombre"
                       required maxlength="100">
            </div>

            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" class="form-control" id="apellidos" placeholder="Apellidos"
                       ng-model="register.apellidos" required maxlength="100">
            </div>

            <div class="form-group">
                <label for="idServicio">Servicio</label>
                <select class="form-control" id="idServicio" placeholder="Servicio" ng-model="register.idServicio"
                        required>
                    <option value=""></option>
                    <option ng-repeat="option in service" value="[[option.pk]]">[[option.fields.nombre]]</option>
                </select>
            </div>

            <div class="form-group">
                <label for="aniosExperiencia">Años Experiencia</label>
                <input type="number" class="form-control" id="aniosExperiencia" placeholder="Años Experiencia"
                       ng-model="register.aniosExperiencia" required maxlength="2">
            </div>

            <div class="form-group">
                <label for="telefono">Teléfono</label>
                <input type="number" class="form-control" id="telefono" placeholder="Teléfono"
                       ng-model="register.telefono" required maxlength="7">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="form-group">
                    <label for="correoElectronico">Correo Electrónico</label>
                    <input type="email" class="form-control" id="correoElectronico"
                           placeholder="Correo Electrónico" ng-model="register.correoElectronico" required
                           maxlength="50">
                </div>

                <div class="form-group">
                    <label for="contrasenia">Contraseña</label>
                    <input type="password" class="form-control" id="contrasenia" placeholder="Contraseña"
                           ng-model="register.contrasenia" required maxlength="15">
                </div>

                <div class="form-group">
                    <label for="foto">Foto</label>
                    <input id="foto" type="file" accept="image/*" image="fotoCompressed"
                           resize-max-height="480" resize-max-width="640"
                           resize-quality="0.3"
                           resize-type="image/jpg" required/>
                </div>

                <div class="form-group">
                    <div class="col-md-4"></div>
                    <div class="col-md-4"><img class="img-thumbnail" data-holder-rendered="true"
                                               src="http://es.fakenamegenerator.com/images/sil-male.png"
                                               style="width: 100%;"
                                               ng-src="[[fotoCompressed.compressed.dataURL]]"/></div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </div>

        <div class="col-md-12 text-center">
            <input type="submit" class="btn btn-default" value="Registrar">
            <input type="reset" class="btn btn-default" value="Cancelar">
        </div>
    </form>
</div>

{% endblock %}